// ─── MARGIN RULES ─────────────────────────────────────────────────────────────
export const MARGIN_RULES_FE = {
  "Tapware":                           { margin: 35, overThreshold: 60, threshold: 150, capAtRRP: true },
  "Accessories":                       { margin: 35, overThreshold: 60, threshold: 150, capAtRRP: true },
  "Showers":                           { margin: 35, overThreshold: 60, threshold: 150, capAtRRP: true },
  "Basins":                            { margin: 65  },
  "Sinks":                             { margin: 80  },
  "Vanities":                          { margin: 250 }, "Cabinets": { margin: 250 }, "Laundry Cabinets": { margin: 250 },
  "Toilets":                           { margin: 175 }, "Toilets Johnson Suisse": { margin: 300 },
  "Toilets Under $300":                { hardMin: 300 },
  "Shaving Cabinet":                   { margin: 150 }, "Tiles": { margin: 35 }, "Saunas": { margin: 300 },
  "Bathtubs":                          { margin: 300 }, "Spa Bathtubs": { margin: 500 },
  "Riva Transparent Bathtubs":         { margin: 700 },
  "Shower Screens Wall-to-Wall":       { margin: 250 },
  "Shower Screens Covey Return Panel": { margin: 125 },
  "Heating":                           { margin: 100 }, "Lighting": { margin: 100 },
  "Toilet Paper Holders":              { hardMin: 30 }, "Robe Hooks": { hardMin: 20 },
};

// ─── WEIGHT RULES ─────────────────────────────────────────────────────────────
export const WEIGHT_RULES_FE = {
  "Tapware": "formula", "Accessories": "formula", "Showers": "formula",
  "Heating": 150, "Lighting": 150,
  "Shower Screens": 900, "Bathtubs": 900, "Spa Bathtubs": 900,
  "Vanities": 150, "Toilets": 150, "Mirrors": 20, "Basins": 20, "Sinks": 20,
  "Tiles": 150, "Saunas": 900,
};

// ─── CATEGORIES ───────────────────────────────────────────────────────────────
export const ALL_CATEGORIES = [
  "Tapware","Accessories","Showers","Shower Screens","Bathtubs","Vanities","Basins",
  "Mirrors","Heating","Lighting","Kitchen","Laundry","Bidets","Toilets","Tiles","Sinks",
  "Shaving Cabinet","Smart Toilet","Saunas","Toilet Paper Holders","Robe Hooks",
  "Laundry Cabinets","Toilets Johnson Suisse","Toilets Under $300",
  "Riva Transparent Bathtubs","Spa Bathtubs","Shower Screens Wall-to-Wall",
  "Shower Screens Covey Return Panel",
];

// ─── TAG SCHEMAS ──────────────────────────────────────────────────────────────
export const TAG_FIELD_DEFS = {
  brand:         { prefix: "Brand_",         label: "Brand"         },
  colour:        { prefix: "Colour_",        label: "Colour"        },
  style:         { prefix: "Style_",         label: "Style"         },
  configuration: { prefix: "Configuration_", label: "Configuration" },
  size:          { prefix: "Size_",          label: "Size Range"    },
  shape:         { prefix: "Shape_",         label: "Shape"         },
  finish:        { prefix: "Finish_",        label: "Finish"        },
};

export const SCHEMAS_FE = {
  styleOnly:       ["style"],
  brandColourOnly: [],
  configOnly:      ["configuration"],
  configSize:      ["configuration", "size"],
  configSizeStyle: ["configuration", "size", "style"],
  sizeOnly:        ["size"],
  sizeStyle:       ["size", "style"],
  shapeOnly:       ["shape"],
  tileSchema:      ["size", "finish"],
};

// ─── PRODUCT TAG MAP ──────────────────────────────────────────────────────────
export const PRODUCT_TAG_MAP_FE = {
  "Basin Mixer":               { collection:"Basin Mixers",                schema:"styleOnly",       styleOptions:["Contemporary","Traditional","Smart Bathroom"] },
  "Tall Basin Mixer":          { collection:"Tall Basin Mixers",           schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Sink Mixer":                { collection:"Sink Mixers",                 schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Pull-Out Sink Mixer":       { collection:"Pull-Out Sink Mixers",        schema:"styleOnly",       styleOptions:["Contemporary"] },
  "Free Standing Bath Mixer":  { collection:"Free Standing Bath Mixers",   schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Heated Towel Rails":        { collection:"Heated Towel Rails",          schema:"configSize",      configOptions:["Towel Bars","Single Towel Rails","Double Towel Rails"], extraFields:["style"], styleOptions:["Smart Bathrooms"] },
  "Non-Heated Towel Rails":    { collection:"Non-Heated Towel Rails",      schema:"configOnly",      configOptions:["Towel Rails"] },
  "Robe Hooks":                { collection:"Robe Hooks",                  schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Toilet Accessories":        { collection:"Toilet Accessories",          schema:"brandColourOnly" },
  "Soap Dish Holders":         { collection:"Soap Dish Holders",           schema:"brandColourOnly" },
  "Shower on Rails":           { collection:"Shower on Rails",             schema:"styleOnly",       styleOptions:["Contemporary","Traditional","Hamptons"] },
  "Hand Held Showers":         { collection:"Hand Held Showers",           schema:"styleOnly",       styleOptions:["Contemporary"] },
  "Shower Systems":            { collection:"Shower Systems",              schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Shower Heads":              { collection:"Shower Heads",                schema:"styleOnly",       styleOptions:["Contemporary","Traditional"] },
  "Shower Arms":               { collection:"Shower Arms",                 schema:"brandColourOnly" },
  "Undermount Sinks":          { collection:"Undermount Sinks",            schema:"configOnly",      configOptions:["Single Bowl","Double Bowl"] },
  "Overmount Sinks":           { collection:"Overmount Sinks",             schema:"configOnly",      configOptions:["Single Bowl","Double Bowl"] },
  "Kitchen Accessories":       { collection:"Kitchen Accessories",         schema:"brandColourOnly" },
  "Corner Baths":              { collection:"Corner Baths",                schema:"styleOnly",       styleOptions:["Contemporary"] },
  "Freestanding Baths":        { collection:"Freestanding Baths",          schema:"styleOnly",       styleOptions:["Contemporary","Luxury"] },
  "Spa Baths":                 { collection:"Spa Baths",                   schema:"brandColourOnly" },
  "Built in Baths":            { collection:"Built In Baths",              schema:"brandColourOnly" },
  "Framed Shower Screens":     { collection:"Framed Shower Screens",        schema:"configOnly", configOptions:["Pivot","Sliding"] },
  "Semi-Frameless Shower Screens":{ collection:"Semi-Frameless Shower Screens",schema:"configOnly", configOptions:["Pivot","Sliding"] },
  "Frameless Shower Screens":  { collection:"Frameless Shower Screens",     schema:"brandColourOnly" },
  "Wall Hung Vanities":        { collection:"Wall Hung Vanities",          schema:"configSize",      configOptions:["Single Bowl","Double Bowl"] },
  "Floor Standing Vanities":   { collection:"Floor Standing Vanities",     schema:"configSize",      configOptions:["Single Bowl","Double Bowl"] },
  "Tall Boys":                 { collection:"Tall Boys",                   schema:"brandColourOnly" },
  "Above Counter Basins":      { collection:"Above Counter Basins",        schema:"shapeOnly",       shapeOptions:["Round","Rectangle","Oval"] },
  "Under Counter Basins":      { collection:"Under Counter Basins",        schema:"brandColourOnly" },
  "Wall Hung Basins":          { collection:"Wall Hung Basins",            schema:"brandColourOnly" },
  "LED Mirrors":               { collection:"LED Mirrors",                 schema:"shapeOnly",       shapeOptions:["Round","Rectangle"] },
  "Non-LED Mirrors":           { collection:"Non-LED Mirrors",             schema:"shapeOnly",       shapeOptions:["Round","Rectangle"] },
  "Magnifying Mirrors":        { collection:"Magnifying Mirrors",          schema:"brandColourOnly" },
  "Wall Lights":               { collection:"Wall Lights",                 schema:"styleOnly",       styleOptions:["Modern","Contemporary"] },
  "Exhausts":                  { collection:"Exhausts",                    schema:"brandColourOnly" },
  "Laundry Cabinets":          { collection:"Laundry Cabinets",            schema:"sizeOnly" },
  "Laundry Sinks":             { collection:"Laundry Sinks",               schema:"configOnly",      configOptions:["Single Bowl","Double Bowl"] },
  "Bidets & Washlets":         { collection:"Bidets & Washlets",           schema:"styleOnly",       styleOptions:["Smart Bathroom"] },
  "Back to Wall Smart Toilets":{ collection:"Back to Wall Smart Toilets",  schema:"styleOnly",       styleOptions:["Smart Bathroom"] },
  "Rimless Smart Toilets":     { collection:"Rimless Smart Toilets",       schema:"styleOnly",       styleOptions:["Smart Bathroom"] },
  "Wall Hung Smart Toilets":   { collection:"Wall Hung Smart Toilets",     schema:"styleOnly",       styleOptions:["Smart Bathroom"] },
  "Rectangle Tiles":           { collection:"Rectangle Tiles",             schema:"tileSchema",      noBrand:true, finishOptions:["Matte","Gloss"] },
  "Square Tiles":              { collection:"Square Tiles",                schema:"tileSchema",      noBrand:true, finishOptions:["Matte","Gloss"] },
  "Mosaic Tiles":              { collection:"Mosaic Tiles",                schema:"brandColourOnly", noBrand:true, extraFields:["finish"], finishOptions:["Matte","Gloss"] },
};

export const ALL_PRODUCT_TYPES_FLAT = Object.keys(PRODUCT_TAG_MAP_FE).sort();

// ─── TITLE FORMATS ────────────────────────────────────────────────────────────
export const PRODUCT_TITLE_FORMATS = {
  "Basin Mixer":                    { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Tall Basin Mixer":               { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Sink Mixer":                     { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Pull-Out Sink Mixer":            { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Free Standing Bath Mixer":       { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Wall Mixer":                     { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Bath Spouts / Outlets":          { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Heated Towel Rails":             { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add size at end — consider Length" },
  "Non-Heated Towel Rails":         { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add size at end — consider Length" },
  "Robe Hooks":                     { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size needed (under 100mm)" },
  "Toilet Accessories":             { parts:["Brand","Collection","Product Type","Colour"],                            note:"" },
  "Soap Dish Holders":              { parts:["Brand","Collection","Product Type","Colour"],                            note:"" },
  "Channel Grates":                 { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add size at end — consider Length" },
  "Point Drains":                   { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add size at end — consider Length" },
  "Basin Wastes":                   { parts:["Brand","Collection","Product Type","Colour"],                            note:"" },
  "Shower on Rails":                { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size for basic showers (under 100mm)" },
  "Hand Held Showers":              { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size for basic showers (under 100mm)" },
  "Shower Systems":                 { parts:["Brand","Collection","Product Type","Colour"],                            note:"No size for basic showers (under 100mm)" },
  "Shower Heads":                   { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add Size — consider Head dimension" },
  "Shower Arms":                    { parts:["Brand","Collection","Product Type","Size","Colour"],                     note:"Add Size — consider Height or Length according to direction of Arm" },
  "Framed Shower Screens":          { parts:["Brand","Collection","Framing","Type of Shower Screen","Colour","Size"],  note:"" },
  "Semi-Frameless Shower Screens":  { parts:["Brand","Collection","Framing","Type of Shower Screen","Colour","Size"],  note:"" },
  "Frameless Shower Screens":       { parts:["Brand","Collection","Framing","Type of Shower Screen","Colour","Size"],  note:"" },
  "Corner Baths":                   { parts:["Brand","Collection","Type of Bath","Colour","Size"],                     note:"Consider Length" },
  "Freestanding Baths":             { parts:["Brand","Collection","Type of Bath","Colour","Size"],                     note:"Consider Length" },
  "Spa Baths":                      { parts:["Brand","Collection","Type of Bath","Colour","Size"],                     note:"Consider Length" },
  "Built in Baths":                 { parts:["Brand","Collection","Type of Bath","Colour","Size"],                     note:"Consider Length" },
  "Wall Hung Vanities":             { parts:["Brand","Collection","Colour","Size","Bowl Configuration","Vanity Type"], note:"Consider Length" },
  "Floor Standing Vanities":        { parts:["Brand","Collection","Colour","Size","Bowl Configuration","Vanity Type"], note:"Consider Length" },
  "Tall Boys":                      { parts:["Brand","Collection","Colour","Size","Vanity Type"],                      note:"Consider Length and Height" },
  "Mirrored Shaving Cabinets":      { parts:["Brand","Collection","Colour","Cabinet Type","Size"],                     note:"Consider Length or Height according to direction of cabinet" },
  "LED Mirrored Shaving Cabinets":  { parts:["Brand","Collection","Colour","Cabinet Type","Size"],                     note:"Consider Length or Height according to direction of cabinet" },
  "Above Counter Basins":           { parts:["Brand","Collection","Basin Type","Colour","Size"],                       note:"Consider Length" },
  "Under Counter Basins":           { parts:["Brand","Collection","Basin Type","Colour","Size"],                       note:"Consider Length" },
  "Wall Hung Basins":               { parts:["Brand","Collection","Basin Type","Colour","Size"],                       note:"Consider Length" },
  "Freestanding Basins":            { parts:["Brand","Collection","Basin Type","Colour","Size"],                       note:"Consider Length AND Height" },
  "Undermount Sinks":               { parts:["Brand","Collection","Sink Type","Colour","Size"],                        note:'Consider Length. Add "Kitchen Accessories" if applicable' },
  "Overmount Sinks":                { parts:["Brand","Collection","Sink Type","Colour","Size"],                        note:'Consider Length. Add "Kitchen Accessories" if applicable' },
  "Laundry Sinks":                  { parts:["Brand","Collection","Sink Type","Colour","Size"],                        note:"Consider Length" },
  "Kitchen Accessories":            { parts:["Brand","Collection","Product Type","Colour","Size"],                     note:"" },
  "LED Mirrors":                    { parts:["Brand","Collection","Shape","Mirror Type","Colour","Size"],              note:"Consider Length and Height" },
  "Non-LED Mirrors":                { parts:["Brand","Collection","Shape","Mirror Type","Colour","Size"],              note:"Consider Length and Height" },
  "Magnifying Mirrors":             { parts:["Brand","Collection","Shape","Mirror Type","Colour","Size"],              note:"Consider Length and Height" },
  "Heated Towel Rails (Heating)":   { parts:["Brand","Collection","Type of Heating","Colour","Size"],                  note:"Size if applicable" },
  "Hand Dryers":                    { parts:["Brand","Collection","Type","Colour","Size"],                             note:"Use full dimension for Size" },
  "Wall Lights":                    { parts:["Brand","Collection","Type of Lighting","Colour","Size"],                 note:"Consider Length or Height according to direction of the light" },
  "Exhausts":                       { parts:["Brand","Collection","Type of Lighting","Colour","Size"],                 note:"Size if applicable" },
  "Bidets & Washlets":              { parts:["Brand","Collection","Bidet Type","Control Type","Washlet Shape","Colour"],note:"Washlet Shape if applicable" },
  "Back to Wall Smart Toilets":     { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Rimless Smart Toilets":          { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Wall Hung Smart Toilets":        { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Back to Wall Toilets":           { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Close Coupled Toilets":          { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Wall Faced Toilets":             { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Rimless Toilets":                { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "In-Wall Cisterns":               { parts:["Brand","Collection","Type","Colour"],                                    note:"" },
  "Integrated Smart Toilets":       { parts:["Brand","Collection","Toilet Type","Bidet Type","Control Type","Washlet Shape","Colour"], note:"Smart Toilet format" },
  "Rectangle Tiles":                { parts:["Brand","Collection","Colour","Finish","Size","Shape Tile (PER BOX)"],    note:"Always state unit: PER BOX / PER PACK / PER SLAB / PER TILE" },
  "Square Tiles":                   { parts:["Brand","Collection","Colour","Finish","Size","Shape Tile (PER BOX)"],    note:"Always state unit: PER BOX / PER PACK / PER SLAB / PER TILE" },
  "Mosaic Tiles":                   { parts:["Brand","Collection","Colour","Finish","Size","Shape Tile (PER BOX)"],    note:"Always state unit: PER BOX / PER PACK / PER SLAB / PER TILE" },
  "Laundry Cabinets":               { parts:["Brand","Collection","Product Type","Colour","Size"],                     note:"Consider Length" },
};

export const CATEGORY_TITLE_FORMATS = {
  "Tapware":        { parts:["Brand","Collection","Product Type","Size","Colour"],                      note:"No size for basic tapware (under 100mm)" },
  "Accessories":    { parts:["Brand","Collection","Product Type","Size","Colour"],                      note:"" },
  "Showers":        { parts:["Brand","Collection","Product Type","Size","Colour"],                      note:"No size for basic showers (under 100mm)" },
  "Shower Screens": { parts:["Brand","Collection","Framing","Type of Shower Screen","Colour","Size"],   note:"" },
  "Bathtubs":       { parts:["Brand","Collection","Type of Bath","Colour","Size"],                      note:"Consider Length" },
  "Vanities":       { parts:["Brand","Collection","Colour","Size","Bowl Configuration","Vanity Type"],  note:"Consider Length" },
  "Shaving Cabinet":{ parts:["Brand","Collection","Colour","Cabinet Type","Size"],                      note:"Consider Length or Height" },
  "Basins":         { parts:["Brand","Collection","Basin Type","Colour","Size"],                        note:"Consider Length" },
  "Sinks":          { parts:["Brand","Collection","Sink Type","Colour","Size"],                         note:"Consider Length" },
  "Mirrors":        { parts:["Brand","Collection","Shape","Mirror Type","Colour","Size"],               note:"Consider Length and Height" },
  "Heating":        { parts:["Brand","Collection","Type of Heating","Colour","Size"],                   note:"" },
  "Lighting":       { parts:["Brand","Collection","Type of Lighting","Colour","Size"],                  note:"Consider Length or Height" },
  "Bidets":         { parts:["Brand","Collection","Bidet Type","Control Type","Washlet Shape","Colour"],note:"" },
  "Toilets":        { parts:["Brand","Collection","Type","Colour"],                                     note:"" },
  "Smart Toilet":   { parts:["Brand","Collection","Toilet Type","Bidet Type","Control Type","Washlet Shape","Colour"], note:"" },
  "Tiles":          { parts:["Brand","Collection","Colour","Finish","Size","Shape Tile (PER BOX)"],     note:"Always state unit" },
  "Kitchen":        { parts:["Brand","Collection","Product Type","Colour","Size"],                      note:"" },
  "Laundry":        { parts:["Brand","Collection","Product Type","Colour","Size"],                      note:"Consider Length" },
  "default":        { parts:["Brand","Collection","Product Type","Colour"],                             note:"" },
};

// ─── DESCRIPTION CONFIG ───────────────────────────────────────────────────────
export const DESCRIPTION_FEATURES = {
  Accessories: ["colour","size","shape","material","type","wels","flowRate","welsReg","ipRating","voltage","additional"],
  Tapware:     ["colour","size","material","type","wels","flowRate","welsReg","additional"],
  Basins:      ["colour","size","material","mounting","compatible","additional"],
  Vanities:    ["colour","size","material","mounting","bowl","drawer","mechanism","handles","additional"],
  Showers:     ["colour","size","material","type","wels","flowRate","additional"],
  Mirrors:     ["colour","size","shape","type","ipRating","voltage","additional"],
  Toilets:     ["colour","size","type","flushing","waterRating","additional"],
  Tiles:       ["colour","size","finish","shape","coverage","additional"],
  default:     ["colour","size","material","type","additional"],
};

export const FEATURE_LABELS = {
  colour:"Colour", size:"Size", shape:"Shape", material:"Material", type:"Type",
  wels:"WELS Rating", flowRate:"Flow Rate", welsReg:"WELS Reg. No.",
  ipRating:"IP Rating", voltage:"Voltage", additional:"Additional Information",
  mounting:"Mounting", compatible:"Compatible with", bowl:"Bowl Option",
  drawer:"Drawer/Door", mechanism:"Mechanism", handles:"Handles",
  flushing:"Flushing System", waterRating:"Water Rating",
  finish:"Finish", coverage:"Coverage (per box/pack)",
};

export const PRODUCT_SPEC_TAGS = [
  "Gooseneck", "Lead Free", "Watermark Approved", "WELS Approved",
  "Wall Mounted", "Floor Mounted", "Freestanding", "Back to Wall",
  "Rimless", "Dual Flush", "Single Lever", "Double Handle",
  "Thermostatic", "Brushed", "Matte", "Polished",
];